# CI/CD Pipeline for TWCC's project

name: TWCC CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # action that checks out repository onto the runner
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: mvn clean test
  
  checkstyle:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkstyle
        run: mvn site
  
  static-analysis-tool:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Static Analysis Bug Finder Tool
        run: echo "TODO - Update static analysis bug finder tool script"
