# CI/CD Workflow for TWCC's project

name: TWCC CI/CD Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./service
    steps:
      - uses: actions/checkout@v3 # action that checks out repository onto the runner
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn clean test

      - name: Checkstyle
        run: mvn site

  reports:
    runs-on: ubuntu-latest
    steps:
      - name: Screenshot Checkstyle
        uses: swinton/screenshot-website@v1.x
        with:
          source: ./service/target/site/index.html
          destination: ./service/reports/t3-checkstyle-report.png
